<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<OutputType>WinExe</OutputType>
	<TargetFramework>net8.0-windows</TargetFramework>
	<UseWPF>true</UseWPF>
	<Nullable>enable</Nullable>
	<AssemblyName>DebtPayoffCalculator</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
	<PackageReference Include="LiveChartsCore.SkiaSharpView.WPF" Version="2.0.0-rc2" />
	<PackageReference Include="CsvHelper" Version="30.0.1" />
  </ItemGroup>

</Project>
